# Generated by Django 3.1.7 on 2021-03-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20210310_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomID',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
