# Generated by Django 3.1.7 on 2021-03-13 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_auto_20210312_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 23, 47, 41, 703615)),
        ),
    ]
