# Generated by Django 3.1.7 on 2021-03-24 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0009_auto_20210323_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 15, 58, 58, 470354)),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
